import Head from "next/head";

// import connectDB from "../lib/dbConnect";
// import User from "../models/User";

import { LayoutLogin } from "../components/Containers/LayoutLogin";
import { LoginForm } from "../components/Containers/LoginForm";

export default function index() {
  return (
    <>
      <Head>
        <title>Lol Clone - Emanuel Mamani</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutLogin>
        <LoginForm />
      </LayoutLogin>
    </>
  );
}

// export async function getServerSideProps() {
//   try {
//     await connectDB();

//     const resp = await User.find({});
//     console.log("resp", resp);

//     const users = resp.map((doc) => {
//       const user = doc.toObject();
//       user._id = `${user._id}`;
//       return user;
//     });

//     return {
//       props: {
//         users,
//       },
//     };
//   } catch (error) {
//     console.log(error);
//   }
// }
